### ISSUE TITLE
Cost Collection crashes upon detecting a Sponsorship subscription

### ISSUE THREAD

**Issue by Jelledb** [meshcloud/collie-cli#11]
When running `tenant costs ...` the command crashes when the program encounters at least one Azure subscription of the type `Sponsorship subscription`. See the following logs as an example:

```
DEBUG getCostInformation: {"code":0,"stderr":"Command group 'consumption' is in preview. It may be changed/removed in a future release.\n","stdout":"[]\n"}
DEBUG Fetched 0 cost infos from Azure
DEBUG Quering Azure for tenant Microsoft Azure Sponsorship: {"from":"2021-05-01T00:00:00.000Z","to":"2021-05-31T23:59:59.000Z"}
DEBUG getCostInformation: {"code":1,"stderr":"Command group 'consumption' is in preview. It may be changed/removed in a future release.\n(422) Cost Management supports only Enterprise Agreement, Web direct and Microsoft Customer Agreement offer types. Subscription <sub-id> is not associated with a valid offer type.Cost Management supports only Enterprise Agreement, Web direct and Microsoft Customer Agreement offer types. Subscription <sub-id> is not associated with a valid offer type. (Request ID: 6e7bad96-a511-48fa-86fd-cf4569b26e70)\n","stdout":""}
ERROR SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at BasicAzureCliFacade.getCostInformation (file:///Users/---/dev/mc/collie/src/azure/basic-azure-cli-facade.ts:86:17)
    at async AutoInstallAzureCliModuleDecorator.wrapCallWithInstallInterception (file:///Users/---/dev/mc/collie/src/azure/auto-install-azure-cli-module-decorator.ts:56:14)
    at async AutoInstallAzureCliModuleDecorator.getCostInformation (file:///Users/---/dev/mc/collie/src/azure/auto-install-azure-cli-module-decorator.ts:43:12)
    at async RetryingAzureCliFacadeDecorator.getCostInformation (file:///Users/---/dev/mc/collie/src/azure/retrying-azure-cli-facade-decorator.ts:38:14)
    at async AzureMeshAdapter.getTenantCostsForWindow (file:///Users/---/dev/mc/collie/src/azure/azure-mesh-adapter.ts:71:28)
    at async AzureMeshAdapter.listTenantCosts (file:///Users/---/dev/mc/collie/src/azure/azure-mesh-adapter.ts:51:24)
    at async Promise.all (index 0)
    at async MultiMeshAdapter.listTenantCosts (file:///Users/---/dev/mc/collie/src/mesh/multi-mesh-adapter.ts:26:13)
    at async Command.listTenantsCostAction [as fn] (file:///Users/---/dev/mc/collie/src/commands/tenant.command.ts:113:26)
✘-1 ~/dev/mc/collie/src [develop|✚ 4…2] 
```

**Comment by tfelix** [comment]
After merging of the PR can you re-try the collection? But you probably need to not configure a management group. However how the management group collection API deals with this kind of subscriptions could also be interesting. I assume they are just not getting listed then in the response?
