### ISSUE TITLE
tenant list returning Could not parse JSON

### ISSUE THREAD

**Issue by ten-cloudops** [meshcloud/collie-cli#110]
ERROR Could not parse JSON:

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJsonWithLog (file://$deno$/bundle.js:15910:21)
    at BasicAzureCliFacade.listTags (file://$deno$/bundle.js:17175:16)
    at async AutoInstallAzureCliModuleDecorator.wrapCallWithInstallInterception (file://$deno$/bundle.js:17420:20)
    at async AutoInstallAzureCliModuleDecorator.listTags (file://$deno$/bundle.js:17404:16)
    at async file://$deno$/bundle.js:17268:20
    at async RetryingAzureCliFacadeDecorator.retryable (file://$deno$/bundle.js:17283:20)
    at async RetryingAzureCliFacadeDecorator.listTags (file://$deno$/bundle.js:17267:16)
    at async file://$deno$/bundle.js:16868:26
    at async Promise.all (index 0)

Running on MacOS and connected to Azure and AWS

**Comment by DorukAkinci** [comment]
Could you execute `az login` command first and try again? As far as i know this issue is related to that and it is a known bug which will be solved in the future update

**Comment by ten-cloudops** [comment]
getting the same even after the az login command. facing the same issue if I have only AWS or Azure connected

**Comment by ten-cloudops** [comment]
I found that while running the collie tenant list it is trying to scan a subscription which is not mine (not sure from where it is coming)
\ az tag list --subscription **6a7f2445-1f25-4638-b16b-16a9cee5c95f**

is there a way to list or force only specific subscriptions ?

**Comment by Jelledb** [comment]
> I found that while running the collie tenant list it is trying to scan a subscription which is not mine (not sure from where it is coming)
> \ az tag list --subscription **6a7f2445-1f25-4638-b16b-16a9cee5c95f**
> 
> is there a way to list or force only specific subscriptions ?

That's interesting, the subscription does pop up when we initially run `az account list` then. Do you have any idea why that subscription would be included by Azure CLI?
What error is thrown when it tries to `az tag list` for that subscription? Perhaps we can catch the exception and continue the collection.

**Comment by ten-cloudops** [comment]
> > I found that while running the collie tenant list it is trying to scan a subscription which is not mine (not sure from where it is coming)
> > \ az tag list --subscription **6a7f2445-1f25-4638-b16b-16a9cee5c95f**
> > is there a way to list or force only specific subscriptions ?
> 
> That's interesting, the subscription does pop up when we initially run `az account list` then. Do you have any idea why that subscription would be included by Azure CLI?
> What error is thrown when it tries to `az tag list` for that subscription? Perhaps we can catch the exception and continue the collection. Try to run `collie tenant list --debug` and you'll get some additional information

found it , that subscription id has been transferred to a new tenant (along with others) on which I do not have access anymore. It got removed after doing an az logout.
now I am getting this error: 
NotFound: No such file or directory (os error 2)
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at Object.opSync (deno:core/core.js:120:12)
    at openSync (deno:runtime/js/40_files.js:32:22)
    at Object.writeFileSync (deno:runtime/js/40_write_file.js:24:18)
    at MeshTenantRepository.writeFile (file://$deno$/bundle.js:16311:14)
    at MeshTenantRepository.save (file://$deno$/bundle.js:16417:14)
    at CachingMeshAdapterDecorator.getMeshTenants (file://$deno$/bundle.js:17460:33)
    at async file://$deno$/bundle.js:17569:80
    at async QueryStatistics.recordQuery (file://$deno$/bundle.js:18239:24)

**Comment by ten-cloudops** [comment]
fixed I had to removed another subscription from my access, all good now :)
thanks for your help

**Comment by Jelledb** [comment]
> fixed I had to removed another subscription from my access, all good now :)
> thanks for your help

That's great to hear. Let me know if you run into any other issues by opening a new one :-)
