### ISSUE TITLE
command line completions for zsh can not sourced

### ISSUE THREAD

**Issue by felixzieger** [meshcloud/collie-cli#190]
**Describe the bug**

Cliffy generated completions (see `collie completions --help`). For collie sourcing zsh the completions result in an error.

```sh
❯ source <(collie completions zsh)
error: Uncaught Error: Inappropriate ioctl for device (os error 25)
    at Object.consoleSize (deno:runtime/js/40_tty.js:9:16)
    at https://raw.githubusercontent.com/zongwei007/cli-format-deno/v3.x/src/format-config.ts:21:17
```
I can run `collie completions zsh` and the output is shown on stdout, but when I copy-paste that into a file and try to source that I get `collie-completions:245: parse error near >`

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/67903933/204472156-ee417a19-4c21-4b1f-9f42-28339569373b.png">

**Reach of the bug**
All users of Collie who want to use cli completions.

**Impact of the bug**
CLI completions make exploring commands easier.

**To Reproduce**
1. Run `source <(collie completions zsh)`

**Expected behavior**
ZSH sources the completions. Completions work on ZSH.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Version v0.15.0

**Comment by felixzieger** [comment]
This is fixed with v0.17.0
