### ISSUE TITLE
Exception writing collie config file

### ISSUE THREAD

**Issue by JohannesRudolph** [meshcloud/collie-cli#227]
Running in a repo that was not initialized with collie init

```
collie will generate the following platform configurations under ./foundations/f/platforms/

        - az

 ? Select an action to continue › ✔ save & exit
generated new foundation at foundations/f
error: Uncaught NotFound: No such file or directory (os error 2): writefile '/Users/jrudolph/dev/mc/collie-hub/.collie/config.json'
    await Deno.writeTextFile(
    ^
    at async writeFile (ext:deno_fs/30_fs.js:806:7)
    at async CollieConfig.saveToDisk (file:///Users/jrudolph/dev/mc/collie-cli/src/model/CollieConfig.ts:61:5)
    at async CollieConfig.setProperty (file:///Users/jrudolph/dev/mc/collie-cli/src/model/CollieConfig.ts:35:5)
```

**Comment by felixzieger** [comment]
Should be fixed by https://github.com/meshcloud/collie-cli/pull/232
