### ISSUE TITLE
collie tenant list crashes with "Unexecpted end of JSON input"

### ISSUE THREAD

**Issue by felixzieger** [meshcloud/collie-cli#25]
I logged into az and gcloud and ran `collie tenant list --debug`. 

The result is:

```
DEBUG listProjects: {"code":0,"stderr":"","stdout":"[\n  {\n    \"createTime\": \"2021-06-23T07:12:19.599Z\",\n    \"labels\": {\n      \"mesh-customer\": \"managed-customer\",\n      \"mesh-project\": \"test-dev\",\n      \"meshstack_cident\": 
...
\"type\": \"organization\"\n    },\n    \"projectId\": \"meshstack-root\",\n    \"projectNumber\": \"864000543001\"\n  }\n]\n"}

ERROR SyntaxError: Unexpected end of JSON input-a93c-c9e95d079a13
    at JSON.parse (<anonymous>)
    at BasicAzureCliFacade.listTags (file://$deno$/bundle.js:17995:21)
    at async AutoInstallAzureCliModuleDecorator.wrapCallWithInstallInterception (file://$deno$/bundle.js:18189:20)
    at async AutoInstallAzureCliModuleDecorator.listTags (file://$deno$/bundle.js:18178:16)
    at async file://$deno$/bundle.js:18049:20
    at async RetryingAzureCliFacadeDecorator.retryable (file://$deno$/bundle.js:18059:20)
    at async RetryingAzureCliFacadeDecorator.listTags (file://$deno$/bundle.js:18048:16)
    at async file://$deno$/bundle.js:17852:26
    at async Promise.all (index 1)
    at async Promise.all (index 0)
```

**Comment by tfelix** [comment]
Thanks for this report Felix. Could you post the whole DEBUG output please. I think 
```DEBUG listProjects: {"code":0,"stderr":"","stdout":"[\n  {\n    \"createTime\": \"2021-06-23T07:12:19.599Z\",\n    \"labels\": {\n      \"mesh-customer\": \"managed-customer\",\n      \"mesh-project\": \"test-dev\",\n      \"meshstack_cident\": 
...
\"type\": \"organization\"\n    },\n    \"projectId\": \"meshstack-root\",\n    \"projectNumber\": \"864000543001\"\n  }\n]\n"}```
is missing some information in the middle. With that we can look into why deserilization fails for you.

**Comment by felixzieger** [comment]
```
collie tenant list --debug
DEBUG listProjects: {"code":0,"stderr":"","stdout":"[\n  {\n    \"createTime\": \"2021-06-23T07:12:19.599Z\",\n    \"labels\": {\n      \"mesh-customer\": \"managed-customer\",\n      \"mesh-project\": \"test-dev\",\n      \"meshstack_cident\": \"managed_customer\",\n      \"meshstack_environment\": \"dev\",\n      \"meshstack_pident\": \"prefix_test_dev\"\n    },\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"managed'stomer test-dev\",\n    \"parent\": {\n      \"id\": \"36139996503\",\n      \"type\": \"folder\"\n    },\n    \"projectId\": \"managed-custome-test-dev-joo\",\n    \"projectNumber\": \"412358920302\"\n  },\n  {\n    \"createTime\": \"2021-06-22T09:35:33.272Z\",\n    \"labels\": {\n      \"mesh-customer\": \"managed-customer\",\n      \"mesh-project\": \"test-002-dev\",\n      \"meshstack_cident\": \"managed_customer\",\n      \"meshstack_environment\": \"dev\",\n      \"meshstack_pident\": \"prefix_test_002_dev\"\n    },\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"managed'stomer test-002-dev\",\n    \"parent\": {\n      \"id\": \"36139996503\",\n      \"type\": \"folder\"\n    },\n    \"projectId\": \"managed-custome-test-002-d-vnv\",\n    \"projectNumber\": \"170811482129\"\n  },\n  {\n    \"createTime\": \"2021-06-22T08:33:01.528Z\",\n    \"labels\": {\n      \"mesh-customer\": \"managed-customer\",\n      \"mesh-project\": \"test-001-dev\",\n      \"meshstack_cident\": \"managed_customer\",\n      \"meshstack_environment\": \"dev\",\n      \"meshstack_pident\": \"prefix_test_001_dev\"\n    },\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"managed'stomer test-001-dev\",\n    \"parent\": {\n      \"id\": \"36139996503\",\n      \"type\": \"folder\"\n    },\n    \"projectId\": \"managed-custome-test-001-d-8fr\",\n    \"projectNumber\": \"350214060137\"\n  },\n  {\n    \"createTime\": \"2021-05-27T11:26:04.245Z\",\n    \"labels\": {\n      \"mesh-customer\": \"likvid-mobile\",\n      \"mesh-project\": \"demo-project\",\n      \"meshstack_cident\": \"likvid_mobile\",\n      \"meshstack_confidentiality\": \"public\",\n      \"meshstack_pident\": \"prefix_demo_project\"\n    },\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"likvid-mobile demo-project\",\n    \"parent\": {\n      \"id\": \"956712559912\",\n      \"type\": \"folder\"\n    },\n    \"projectId\": \"likvid-mobile-demo-proje-duo\",\n    \"projectNumber\": \"31773893082\"\n  },\n  {\n    \"createTime\": \"2021-05-26T08:53:56.276Z\",\n    \"labels\": {\n      \"mesh-customer\": \"likvid-mobile\",\n      \"mesh-project\": \"new-test-account\",\n      \"meshstack_cident\": \"likvid_mobile\",\n      \"meshstack_confidentiality\": \"public\",\n      \"meshstack_pident\": \"prefix_new_test_account\"\n    },\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"likvid-mobile new-tes'account\",\n    \"parent\": {\n      \"id\": \"956712559912\",\n      \"type\": \"folder\"\n    },\n    \"projectId\": \"likvid-mobile-new-test-a-4nl\",\n    \"projectNumber\": \"632815371940\"\n  },\n  {\n    \"createTime\": \"2021-05-10T14:45:37.651Z\",\n    \"labels\": {\n      \"mesh-customer\": \"managed-customer\",\n      \"mesh-project\": \"collection-test-project-dev\",\n      \"meshstack_cident\": \"managed_customer\",\n      \"meshstack_environment\": \"dev\",\n      \"meshstack_pident\": \"prefix_collection_test_project_dev\"\n    },\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"managed'stomer collect'ect-dev\",\n    \"parent\": {\n      \"id\": \"36139996503\",\n      \"type\": \"folder\"\n    },\n    \"projectId\": \"managed-custome-collection-xfp\",\n    \"projectNumber\": \"1038591166955\"\n  },\n  {\n    \"createTime\": \"2021-05-06T13:41:06.080Z\",\n    \"labels\": {\n      \"mesh-customer\": \"likvid-mobile\",\n      \"mesh-project\": \"new-demo-test\",\n      \"meshstack_cident\": \"likvid_mobile\",\n      \"meshstack_confidentiality\": \"public\",\n      \"meshstack_pident\": \"prefix_new_demo_test\"\n    },\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"likvid-mobile new-demo-test\",\n    \"parent\": {\n      \"id\": \"956712559912\",\n      \"type\": \"folder\"\n    },\n    \"projectId\": \"likvid-mobile-new-demo-t-56n\",\n    \"projectNumber\": \"921781000544\"\n  },\n  {\n    \"createTime\": \"2021-02-23T15:25:04.176Z\",\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"felix-cloudfun-demo-20210223\",\n    \"parent\": {\n      \"id\": \"632614034120\",\n      \"type\": \"organization\"\n    },\n    \"projectId\": \"felix-cloudfun-demo-20210223\",\n    \"projectNumber\": \"225288150285\"\n  },\n  {\n    \"createTime\": \"2021-02-01T09:42:24.991Z\",\n    \"labels\": {\n      \"mesh-customer\": \"meshcloud-qa\",\n      \"mesh-project\": \"meshcloud-qa-7-51-1-gcp\",\n      \"mesh_customerid\": \"meshcloud_qa\",\n      \"mesh_projectid\": \"meshcloud_qa_7_51_1_gcp\",\n      \"mesh_servicename\": \"test\",\n      \"mesh_serviceowner\": \"john_doe\"\n    },\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"meshcloud-qa meshclo'1-1-gcp\",\n    \"parent\": {\n      \"id\": \"901682241866\",\n      \"type\": \"folder\"\n    },\n    \"projectId\": \"cf-meshcloud--meshcloud-qa--d6\",\n    \"projectNumber\": \"683086575551\"\n  },\n  {\n    \"createTime\": \"2020-12-16T17:37:53.261Z\",\n    \"labels\": {\n      \"mesh-customer\": \"likvid-backend\",\n      \"mesh-project\": \"backend-develop\",\n      \"meshstack_cident\": \"likvid_backend\",\n      \"meshstack_confidentiality\": \"public\",\n      \"meshstack_pident\": \"prefix_backend_develop\"\n    },\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"likvid-backend backend-develop\",\n    \"parent\": {\n      \"id\": \"956712559912\",\n      \"type\": \"folder\"\n    },\n    \"projectId\": \"likvid-backend-backend-de-m42\",\n    \"projectNumber\": \"549273465529\"\n  },\n  {\n    \"createTime\": \"2020-12-09T13:57:32.143Z\",\n    \"labels\": {\n      \"mesh-customer\": \"likvid-operations\",\n      \"mesh-project\": \"platform-operations\",\n      \"meshstack_cident\": \"likvid_operations\",\n      \"meshstack_confidentiality\": \"public\",\n      \"meshstack_costcenter\": \"1001\",\n      \"meshstack_pident\": \"prefix_platform_operations\"\n    },\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"likvid-'ations platfor'rations\",\n    \"parent\": {\n      \"id\": \"145203092684\",\n      \"type\": \"folder\"\n    },\n    \"projectId\": \"likvid-operatio-platform-o-t6p\",\n    \"projectNumber\": \"973042291167\"\n  },\n  {\n    \"createTime\": \"2020-10-22T15:37:25.502Z\",\n    \"labels\": {\n      \"mesh-customer\": \"managed-customer\",\n      \"mesh-project\": \"managed-project\",\n      \"meshstack_cident\": \"managed_customer\",\n      \"meshstack_my_special_tag\": \"admin_restricted\",\n      \"meshstack_pident\": \"prefix_managed_project\",\n      \"meshstack_projectowner\": \"admin_changed\",\n      \"meshstack_testreplication\": \"testest\"\n    },\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"managed'stomer managed-project\",\n    \"parent\": {\n      \"id\": \"36139996503\",\n      \"type\": \"folder\"\n    },\n    \"projectId\": \"managed-custome-managed-pr-gqw\",\n    \"projectNumber\": \"401356814624\"\n  },\n  {\n    \"createTime\": \"2020-04-14T16:44:20.523Z\",\n    \"labels\": {\n      \"meshstack_cident\": \"managed_customer\",\n      \"meshstack_pident\": \"prefix_managed_project\"\n    },\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"managed'stomer managed-project\",\n    \"parent\": {\n      \"id\": \"36139996503\",\n      \"type\": \"folder\"\n    },\n    \"projectId\": \"managed-cu-managed-pr-qjwhkz0s\",\n    \"projectNumber\": \"950341347954\"\n  },\n  {\n    \"createTime\": \"2020-04-07T12:31:09.294Z\",\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"likvid-gdm\",\n    \"parent\": {\n      \"id\": \"493343334220\",\n      \"type\": \"folder\"\n    },\n    \"projectId\": \"likvid-gdm\",\n    \"projectNumber\": \"644323545523\"\n  },\n  {\n    \"createTime\": \"2019-12-05T05:51:17.922Z\",\n    \"labels\": {\n      \"mesh-customer\": \"likvid-mobile\",\n      \"mesh-project\": \"develop\",\n      \"meshstack_cident\": \"likvid_mobile\",\n      \"meshstack_confidentiality\": \"public\",\n      \"meshstack_costcenter\": \"1001\",\n      \"meshstack_costcenternumber\": \"2001\",\n      \"meshstack_pident\": \"prefix_develop\"\n    },\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"likvid-mobile develop\",\n    \"parent\": {\n      \"id\": \"956712559912\",\n      \"type\": \"folder\"\n    },\n    \"projectId\": \"likvid-mob-develop-mtihns7f\",\n    \"projectNumber\": \"11435090522\"\n  },\n  {\n    \"createTime\": \"2019-12-05T05:48:38.631Z\",\n    \"labels\": {\n      \"mesh-customer\": \"likvid-mobile\",\n      \"mesh-project\": \"production\",\n      \"meshstack_cident\": \"likvid_mobile\",\n      \"meshstack_confidentiality\": \"internal\",\n      \"meshstack_costcenter\": \"2001\",\n      \"meshstack_pident\": \"prefix_production\"\n    },\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"likvid-mobile production\",\n    \"parent\": {\n      \"id\": \"145203092684\",\n      \"type\": \"folder\"\n    },\n    \"projectId\": \"likvid-mob-production-3576w7yh\",\n    \"projectNumber\": \"95618656077\"\n  },\n  {\n    \"createTime\": \"2019-11-12T14:56:21.240Z\",\n    \"labels\": {\n      \"mesh-customer\": \"likvid-mobile\",\n      \"mesh-project\": \"staging\",\n      \"meshstack_cident\": \"likvid_mobile\",\n      \"meshstack_confidentiality\": \"public\",\n      \"meshstack_costcenter\": \"2001\",\n      \"meshstack_costcenternumber\": \"2001\",\n      \"meshstack_pident\": \"prefix_staging\"\n    },\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"likvid-mobile staging\",\n    \"parent\": {\n      \"id\": \"956712559912\",\n      \"type\": \"folder\"\n    },\n    \"projectId\": \"likvid-mob-staging-wsiyirzx\",\n    \"projectNumber\": \"806545258681\"\n  },\n  {\n    \"createTime\": \"2019-05-31T08:16:08.179Z\",\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"meshstack-infra\",\n    \"parent\": {\n      \"id\": \"634059704700\",\n      \"type\": \"organization\"\n    },\n    \"projectId\": \"meshstack-infra\",\n    \"projectNumber\": \"351831468728\"\n  },\n  {\n    \"createTime\": \"2019-03-12T16:26:55.019Z\",\n    \"lifecycleState\": \"ACTIVE\",\n    \"name\": \"meshstack-root\",\n    \"parent\": {\n      \"id\": \"632614034120\",\n      \"type\": \"organization\"\n    },\n    \"projectId\": \"meshstack-root\",\n    \"projectNumber\": \"864000543001\"\n  }\n]\n"}
ERROR SyntaxError: Unexpected end of JSON input-a93c-c9e95d079a13
    at JSON.parse (<anonymous>)
    at BasicAzureCliFacade.listTags (file://$deno$/bundle.js:17995:21)
    at async AutoInstallAzureCliModuleDecorator.wrapCallWithInstallInterception (file://$deno$/bundle.js:18189:20)
    at async AutoInstallAzureCliModuleDecorator.listTags (file://$deno$/bundle.js:18178:16)
    at async file://$deno$/bundle.js:18049:20
    at async RetryingAzureCliFacadeDecorator.retryable (file://$deno$/bundle.js:18059:20)
    at async RetryingAzureCliFacadeDecorator.listTags (file://$deno$/bundle.js:18048:16)
    at async file://$deno$/bundle.js:17852:26
    at async Promise.all (index 1)
    at async Promise.all (index 0)
```

**Comment by tfelix** [comment]
We merged an improved error logging version to the dev branch. Can you check this version out and please issue the command again? There is now a better error logging when called with the `--debug` flag.

**Comment by felixzieger** [comment]
Sure, here is the output:

```
λ ~/meshcloud/collie-cli/src/ develop ./run.sh tenant list --debug
DEBUG listAccounts: {"code":0,"stderr":"","stdout":"[\n  {\n    \"cloudName\": \"AzureCloud\",\n    \"homeTenantId\": \"5f0e994b-6436-4f58-be96-4dc7bebff827\",\n    \"id\": \"8f25c6cb-7398-4054-8f25-3f950f7b0234\",\n    \"isDefault\": true,\n    \"managedByTenants\": [],\n    \"name\": \"Microsoft Azure Sponsorship\",\n    \"state\": \"Enabled\",\n    \"tenantId\": \"5f0e994b-6436-4f58-be96-4dc7bebff827\",\n    \"user\": {\n      \"name\": \"fzieger@meshcloud.io\",\n      \"type\": \"user\"\n    }\n  },\n  {\n    \"cloudName\": \"AzureCloud\",\n    \"homeTenantId\": \"612f984e-b536-41ab-83df-1388fd6ad66b\",\n    \"id\": \"064a848f-6ca8-45b0-8f8c-51a72e15a9ae\",\n    \"isDefault\": false,\n    \"managedByTenants\": [\n      {\n        \"tenantId\": \"deff24bb-2089-4400-8c8e-f71e680378b2\"\n      }\n    ],\n    \"name\": \"risk-sim.kfw-demo\",\n    \"state\": \"Enabled\",\n    \"tenantId\": \"612f984e-b536-41ab-83df-1388fd6ad66b\",\n    \"user\": {\n      \"name\": \"fzieger@meshcloud.io\",\n      \"type\": \"user\"\n    }\n  },\n  {\n    \"cloudName\": \"AzureCloud\",\n    \"homeTenantId\": \"612f984e-b536-41ab-83df-1388fd6ad66b\",\n    \"id\": \"4a09b064-3c26-401e-b8d6-f572338d05c8\",\n    \"isDefault\": false,\n    \"managedByTenants\": [\n      {\n        \"tenantId\": \"deff24bb-2089-4400-8c8e-f71e680378b2\"\n      }\n    ],\n    \"name\": \"risk-sim.mysandbox\",\n    \"state\": \"Enabled\",\n    \"tenantId\": \"612f984e-b536-41ab-83df-1388fd6ad66b\",\n    \"user\": {\n      \"name\": \"fzieger@meshcloud.io\",\n      \"type\": \"user\"\n    }\n  },\n  {\n    \"cloudName\": \"AzureCloud\",\n    \"homeTenantId\": \"703c8d27-13e0-4836-8b2e-8390c588cf80\",\n    \"id\": \"497d294f-0f5d-4641-b448-93b32fcd9e93\",\n    \"isDefault\": false,\n    \"managedByTenants\": [],\n    \"name\": \"likvid-central-services\",\n    \"state\": \"Enabled\",\n    \"tenantId\": \"703c8d27-13e0-4836-8b2e-8390c588cf80\",\n    \"user\": {\n      \"name\": \"fzieger@meshcloud.io\",\n      \"type\": \"user\"\n    }\n  },\n  {\n    \"cloudName\": \"AzureCloud\",\n    \"homeTenantId\": \"703c8d27-13e0-4836-8b2e-8390c588cf80\",\n    \"id\": \"fde1603e-225d-40d7-8627-732cb379a018\",\n    \"isDefault\": false,\n    \"managedByTenants\": [],\n    \"name\": \"likvid-mobile.tan-gen-app-dev\",\n    \"state\": \"Enabled\",\n    \"tenantId\": \"703c8d27-13e0-4836-8b2e-8390c588cf80\",\n    \"user\": {\n      \"name\": \"fzieger@meshcloud.io\",\n      \"type\": \"user\"\n    }\n  },\n  {\n    \"cloudName\": \"AzureCloud\",\n    \"homeTenantId\": \"703c8d27-13e0-4836-8b2e-8390c588cf80\",\n    \"id\": \"717b13ac-2baa-4899-b90c-c91723f23c21\",\n    \"isDefault\": false,\n    \"managedByTenants\": [],\n    \"name\": \"likvid-mobile.develop\",\n    \"state\": \"Enabled\",\n    \"tenantId\": \"703c8d27-13e0-4836-8b2e-8390c588cf80\",\n    \"user\": {\n      \"name\": \"fzieger@meshcloud.io\",\n      \"type\": \"user\"\n    }\n  },\n  {\n    \"cloudName\": \"AzureCloud\",\n    \"homeTenantId\": \"703c8d27-13e0-4836-8b2e-8390c588cf80\",\n    \"id\": \"abf9fe01-365d-4d12-a09c-89eaf3109c36\",\n    \"isDefault\": false,\n    \"managedByTenants\": [],\n    \"name\": \"likvid-mobile.production\",\n    \"state\": \"Enabled\",\n    \"tenantId\": \"703c8d27-13e0-4836-8b2e-8390c588cf80\",\n    \"user\": {\n      \"name\": \"fzieger@meshcloud.io\",\n      \"type\": \"user\"\n    }\n  },\n  {\n    \"cloudName\": \"AzureCloud\",\n    \"homeTenantId\": \"703c8d27-13e0-4836-8b2e-8390c588cf80\",\n    \"id\": \"f7d81ca9-2a8e-4e11-b4b6-d9128223c4d1\",\n    \"isDefault\": false,\n    \"managedByTenants\": [],\n    \"name\": \"_unused_meshcloud-dev_1\",\n    \"state\": \"Enabled\",\n    \"tenantId\": \"703c8d27-13e0-4836-8b2e-8390c588cf80\",\n    \"user\": {\n      \"name\": \"fzieger@meshcloud.io\",\n      \"type\": \"user\"\n    }\n  },\n  {\n    \"cloudName\": \"AzureCloud\",\n    \"homeTenantId\": \"703c8d27-13e0-4836-8b2e-8390c588cf80\",\n    \"id\": \"0688c9ba-193b-49f3-a3a5-98735a3908df\",\n    \"isDefault\": false,\n    \"managedByTenants\": [],\n    \"name\": \"_unused_meshcloud-dev_0\",\n    \"state\": \"Enabled\",\n    \"tenantId\": \"703c8d27-13e0-4836-8b2e-8390c588cf80\",\n    \"user\": {\n      \"name\": \"fzieger@meshcloud.io\",\n      \"type\": \"user\"\n    }\n  },\n  {\n    \"cloudName\": \"AzureCloud\",\n    \"homeTenantId\": \"703c8d27-13e0-4836-8b2e-8390c588cf80\",\n    \"id\": \"e9044737-232e-4f3a-9b14-3231c04259d6\",\n    \"isDefault\": false,\n    \"managedByTenants\": [],\n    \"name\": \"_unused_meshcloud-dev_2\",\n    \"state\": \"Enabled\",\n    \"tenantId\": \"703c8d27-13e0-4836-8b2e-8390c588cf80\",\n    \"user\": {\n      \"name\": \"fzieger@meshcloud.io\",\n      \"type\": \"user\"\n    }\n  },\n  {\n    \"cloudName\": \"AzureCloud\",\n    \"homeTenantId\": \"703c8d27-13e0-4836-8b2e-8390c588cf80\",\n    \"id\": \"a7d09781-d7a9-4e0b-a93c-c9e95d079a13\",\n    \"isDefault\": false,\n    \"managedByTenants\": [],\n    \"name\": \"managed-customer.managed-project\",\n    \"state\": \"Enabled\",\n    \"tenantId\": \"703c8d27-13e0-4836-8b2e-8390c588cf80\",\n    \"user\": {\n      \"name\": \"fzieger@meshcloud.io\",\n      \"type\": \"user\"\n    }\n  }\n]\n"}
DEBUG listTags: {"code":0,"stderr":"","stdout":"[\n  {\n    \"count\": {\n      \"type\": \"Total\",\n      \"value\": 1\n    },\n    \"id\": \"/subscriptions/4a09b064-3c26-401e-b8d6-f572338d05c8/tagNames/sandbox\",\n    \"tagName\": \"sandbox\",\n    \"values\": [\n      {\n        \"count\": {\n          \"type\": \"Total\",\n          \"value\": 1\n        },\n        \"id\": \"/subscriptions/4a09b064-3c26-401e-b8d6-f572338d05c8/tagNames/sandbox/tagValues/true\",\n        \"tagValue\": \"true\"\n      }\n    ]\n  },\n  {\n    \"count\": {\n      \"type\": \"Total\",\n      \"value\": 1\n    },\n    \"id\": \"/subscriptions/4a09b064-3c26-401e-b8d6-f572338d05c8/tagNames/meshstack_CostCenter\",\n    \"tagName\": \"meshstack_CostCenter\",\n    \"values\": [\n      {\n        \"count\": {\n          \"type\": \"Total\",\n          \"value\": 1\n        },\n        \"id\": \"/subscriptions/4a09b064-3c26-401e-b8d6-f572338d05c8/tagNames/meshstack_CostCenter/tagValues/A1524\",\n        \"tagValue\": \"A1524\"\n      }\n    ]\n  },\n  {\n    \"count\": {\n      \"type\": \"Total\",\n      \"value\": 1\n    },\n    \"id\": \"/subscriptions/4a09b064-3c26-401e-b8d6-f572338d05c8/tagNames/meshstack_owner\",\n    \"tagName\": \"meshstack_owner\",\n    \"values\": [\n      {\n        \"count\": {\n          \"type\": \"Total\",\n          \"value\": 1\n        },\n        \"id\": \"/subscriptions/4a09b064-3c26-401e-b8d6-f572338d05c8/tagNames/meshstack_owner/tagValues/mmerck@kpmg.com\",\n        \"tagValue\": \"mmerck@kpmg.com\"\n      }\n    ]\n  },\n  {\n    \"count\": {\n      \"type\": \"Total\",\n      \"value\": 1\n    },\n    \"id\": \"/subscriptions/4a09b064-3c26-401e-b8d6-f572338d05c8/tagNames/meshstack_Environment\",\n    \"tagName\": \"meshstack_Environment\",\n    \"values\": [\n      {\n        \"count\": {\n          \"type\": \"Total\",\n          \"value\": 1\n        },\n        \"id\": \"/subscriptions/4a09b064-3c26-401e-b8d6-f572338d05c8/tagNames/meshstack_Environment/tagValues/sandbox\",\n        \"tagValue\": \"sandbox\"\n      }\n    ]\n  }\n]\n"}
DEBUG listTags: {"code":0,"stderr":"","stdout":"[\n  {\n    \"count\": {\n      \"type\": \"Total\",\n      \"value\": 1\n    },\n    \"id\": \"/subscriptions/0688c9ba-193b-49f3-a3a5-98735a3908df/tagNames/meshstack_cident\",\n    \"tagName\": \"meshstack_cident\",\n    \"values\": [\n      {\n        \"count\": {\n          \"type\": \"Total\",\n          \"value\": 1\n        },\n        \"id\": \"/subscriptions/0688c9ba-193b-49f3-a3a5-98735a3908df/tagNames/meshstack_cident/tagValues/testpubuducustom\",\n        \"tagValue\": \"testpubuducustom\"\n      }\n    ]\n  },\n  {\n    \"count\": {\n      \"type\": \"Total\",\n      \"value\": 1\n    },\n    \"id\": \"/subscriptions/0688c9ba-193b-49f3-a3a5-98735a3908df/tagNames/meshstack_pident\",\n    \"tagName\": \"meshstack_pident\",\n    \"values\": [\n      {\n        \"count\": {\n          \"type\": \"Total\",\n          \"value\": 1\n        },\n        \"id\": \"/subscriptions/0688c9ba-193b-49f3-a3a5-98735a3908df/tagNames/meshstack_pident/tagValues/prefix-test-cu-74u6gz\",\n        \"tagValue\": \"prefix-test-cu-74u6gz\"\n      }\n    ]\n  }\n]\n"}
DEBUG listTags: {"code":1,"stderr":"ERROR: (AuthorizationFailed) The client 'fzieger@meshcloud.io' with object id 'ea472944-084f-4a86-8db2-f8b8e3200996' does not have authorization to perform action 'Microsoft.Resources/subscriptions/tagNames/read' over scope '/subscriptions/064a848f-6ca8-45b0-8f8c-51a72e15a9ae' or the scope is invalid. If access was recently granted, please refresh your credentials.\n","stdout":""}
ERROR Could not parse JSON:
ERROR SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJsonWithLog (file:///Users/felix/meshcloud/collie-cli/src/json.ts:5:17)
    at BasicAzureCliFacade.listTags (file:///Users/felix/meshcloud/collie-cli/src/azure/basic-azure-cli-facade.ts:83:12)
    at async AutoInstallAzureCliModuleDecorator.wrapCallWithInstallInterception (file:///Users/felix/meshcloud/collie-cli/src/azure/auto-install-azure-cli-module-decorator.ts:66:14)
    at async AutoInstallAzureCliModuleDecorator.listTags (file:///Users/felix/meshcloud/collie-cli/src/azure/auto-install-azure-cli-module-decorator.ts:43:12)
    at async file:///Users/felix/meshcloud/collie-cli/src/azure/retrying-azure-cli-facade-decorator.ts:48:14
    at async RetryingAzureCliFacadeDecorator.retryable (file:///Users/felix/meshcloud/collie-cli/src/azure/retrying-azure-cli-facade-decorator.ts:68:14)
    at async RetryingAzureCliFacadeDecorator.listTags (file:///Users/felix/meshcloud/collie-cli/src/azure/retrying-azure-cli-facade-decorator.ts:47:12)
    at async file:///Users/felix/meshcloud/collie-cli/src/azure/azure-mesh-adapter.ts:188:22
    at async Promise.all (index 1)
```
