### ISSUE TITLE
Running `collie tenant list` returns error

### ISSUE THREAD

**Issue by SimonTheLeg** [meshcloud/collie-cli#49]
Hey guys, 

I have successfully installed collie, however when I run `collie tenant list` it returns the following error

```sh
❯ collie tenant list
ERROR Could not parse JSON: ounts --output json
ERROR SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJsonWithLog (file://$deno$/bundle.js:17093:21)
    at AwsCliFacade.listAccounts (file://$deno$/bundle.js:17675:32)
    at async AwsMeshAdapter.getMeshTenants (file://$deno$/bundle.js:17736:26)
    at async Promise.all (index 0)
    at async MultiMeshAdapter.getMeshTenants (file://$deno$/bundle.js:17931:17)
    at async CachingMeshAdapterDecorator.getMeshTenants (file://$deno$/bundle.js:18292:29)
    at async Command.listTenantAction [as fn] (file://$deno$/bundle.js:18775:24)
    at async Command.execute (file://$deno$/bundle.js:7117:13)
    at async Command.parse (file://$deno$/bundle.js:7058:24)

```

**Comment by Jelledb** [comment]
@SimonTheLeg could you install the new version and run this again?

**Comment by SimonTheLeg** [comment]
So the original error I guess was that I did not have any aws account selected, and as a result `aws organizations list-accounts --output json` did not return any json

```sh
❯ aws organizations list-accounts --output json
Unable to locate credentials. You can configure credentials by running "aws configure".
```

1. For this case we should definitely build in some logic that bubbles up the original error once we do not receive a valid json


2. However after setting my profile using
```sh
export AWS_PROFILE=<my-great-profile>
```

the command returns a valid json response
```json
❯ aws organizations list-accounts --output json
{
    "Accounts": [
        {
            "Id": "<sanitized>",
            "Arn": "<sanitized>",
            "Email": "<sanitized>",
            "Name": "<sanitized>",
            "Status": "<sanitized>",
            "JoinedMethod": "<sanitized>",
            "JoinedTimestamp": "<sanitized>"
        },
```

but inside collie, I still receive the same error

```sh
❯ collie tenant list
ERROR Could not parse JSON: ounts --output json
ERROR SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJsonWithLog (file://$deno$/bundle.js:17093:21)
    at BasicAzureCliFacade.listTags (file://$deno$/bundle.js:18241:16)
    at async AutoInstallAzureCliModuleDecorator.wrapCallWithInstallInterception (file://$deno$/bundle.js:18478:20)
    at async AutoInstallAzureCliModuleDecorator.listTags (file://$deno$/bundle.js:18462:16)
    at async file://$deno$/bundle.js:18334:20
    at async RetryingAzureCliFacadeDecorator.retryable (file://$deno$/bundle.js:18349:20)
    at async RetryingAzureCliFacadeDecorator.listTags (file://$deno$/bundle.js:18333:16)
    at async file://$deno$/bundle.js:17947:26
    at async Promise.all (index 6)
```

Could it be that collie is executing any of the commands in its own sub-shell? If so I guess it does not have access to the `AWS_PROFILE` environment variable and then the command fails inside collie, but not in my regular shell?

**Comment by tfelix** [comment]
Should be fixed now via https://github.com/meshcloud/collie-cli/issues/56
