### ISSUE TITLE
Found unknown principalType for GCP: deleted, domain

### ISSUE THREAD

**Issue by JohannesRudolph** [meshcloud/collie-cli#77]
I ran `collie tenant iam` on our production GCP org and hit the following issue

```
22:18 $ ./run.sh tenant iam 
Check file:///Users/jrudolph/dev/mc/collie-cli/src/main.ts
WARNING This CLI does not support AWS Role Assignment analysis at the moment. Please keep an eye out for further development on this.
ERROR Error: Found unknown principalType for GCP: deleted
    at GcpMeshAdapter.toPrincipalType (file:///Users/jrudolph/dev/mc/collie-cli/src/gcp/gcp-mesh-adapter.ts:118:15)
    at GcpMeshAdapter.getRoleAssignmentsForTenant (file:///Users/jrudolph/dev/mc/collie-cli/src/gcp/gcp-mesh-adapter.ts:93:33)
```

Another error message from the same spot is `ERROR Error: Found unknown principalType for GCP: domain`.

**Comment by tfelix** [comment]
Domain and Deleted should be now supported as of collie 4.0. Please re-open if you still encounter issues.
