### ISSUE TITLE
Azure collection crashes when refresh token has expired

### ISSUE THREAD

**Issue by Jelledb** [meshcloud/collie-cli#84]
(Was found by @mweber-mc)

ERROR Could not parse JSON for command 'az tag list --subscription 8f25c6cb-7398-4054-8f25-3f950f7b0234'
ERROR Could not parse JSON as an error with code 1 was given. The following stderr is given: ERROR: AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2021-07-21T09:03:57.2770411Z and was inactive for 12:00:00.
Trace ID: b7d4e636-cd69-4894-a248-f6045adb2301
Correlation ID: 85028f2e-e16c-4818-954d-4d92ec0e374a
Timestamp: 2021-07-22 13:29:52Z
To re-authenticate, please run `az login`. If the problem persists, please contact your tenant administrator.
ERROR SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJsonStdoutWithLog (file://$deno$/bundle.js:17082:21)
    at BasicAzureCliFacade.listTags (file://$deno$/bundle.js:18314:16)
    at async AutoInstallAzureCliModuleDecorator.wrapCallWithInstallInterception (file://$deno$/bundle.js:18551:20)
    at async AutoInstallAzureCliModuleDecorator.listTags (file://$deno$/bundle.js:18535:16)
    at async file://$deno$/bundle.js:18407:20
    at async RetryingAzureCliFacadeDecorator.retryable (file://$deno$/bundle.js:18422:20)
    at async RetryingAzureCliFacadeDecorator.listTags (file://$deno$/bundle.js:18406:16)
    at async file://$deno$/bundle.js:18015:26
    at async Promise.all (index 0)

**Comment by tfelix** [comment]
I just tried my Azure Login and still works for me, even after 2 weeks not trying it out. :D

**Comment by tfelix** [comment]
Should actually be fixed. I see every required check in place in the code. It should respond with something like:
```
You are not logged in into Azure CLI. Please login with "az login" or disconnect with "collie config --disconnect Azure".
Error: "WARNING: Please run "az login" to access your accounts."
    at BasicAzureCliFacade.checkForErrors // stack trace going on
```
In case you encounter something like this again please re-open the issue.
